### ISSUE TITLE
Edge domain update

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/experience-platform.en#67]
Issue in ./help/edge/fundamentals/configuring-the-sdk.md

The section about the edgeDomain only mention the "adobedc.net" domain. Based on the Jira ticket AN-248215, the old "omtrdc.net" tracking server can be used for Experience Edge implementation.
So the customer that have a CNAME that maps an "omtrdc.net" tracking server CAN use it also for WebSDK implementation.

**Comment by djwendo** [comment]
Thank you for reporting this. We are reviewing the documentation and will update it shortly.

Tracking internally in https://jira.corp.adobe.com/browse/PLAT-86584

**Comment by srhoades-adobe** [comment]
This issue has been fixed. Thank you.

**Comment by angeli-adobe** [comment]
@srhoades-adobe I don't think that this can be marked as closed. Please look at the JIRA ticket.

**Comment by djwendo** [comment]
Reopening as Jira ticket is not resolved. https://jira.corp.adobe.com/browse/PLAT-86584

**Comment by djwendo** [comment]
This ticket has been resolved. Closing this issue as fixed.
